=== randeepbhatia/books-marketplace/src/test/resources/dataset.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT dataset (livres*, agents*, pdms*, items*)>
<!ELEMENT livres EMPTY>
<!ATTLIST livres
    Categorie CDATA #IMPLIED
    Titre CDATA #IMPLIED
    Auteur CDATA #IMPLIED
    DatePar CDATA #IMPLIED
    Editeur CDATA #IMPLIED
    Format CDATA #IMPLIED
    PrixN CDATA #IMPLIED
    ISBN CDATA #REQUIRED
>
<!ELEMENT agents EMPTY>
<!ATTLIST agents
    nomPDM CDATA #IMPLIED
    nomAgent CDATA #REQUIRED
    argent CDATA #IMPLIED
    categorie CDATA #IMPLIED
>
<!ELEMENT pdms EMPTY>
<!ATTLIST pdms
    nom CDATA #REQUIRED
    adresse CDATA ""
>
<!ELEMENT items EMPTY>
<!ATTLIST items
    ID CDATA #REQUIRED
    ISBN CDATA #IMPLIED
    Etat CDATA #IMPLIED
    Proprio CDATA #IMPLIED
    PrixAchat CDATA #IMPLIED
>

=== randeepbhatia/books-marketplace/src/test/resources/dataset.xml
<!DOCTYPE dataset SYSTEM "dataset.dtd">
<dataset>
    <livres Categorie="Science fiction" Titre="Neuromancien" Auteur="William Gibson" DatePar="2001-01-11" Editeur="J\'ai lu" Format="Poche" PrixN="5.8" ISBN="229030820X" />
    <livres Categorie="Science fiction" Titre="Le grand livre des robots" Auteur="Isaac Asimov" DatePar="1999-09-12" Editeur="Presses de la Cité" Format="Broché" PrixN="32.47" ISBN="2258032903" />
    <livres Categorie="Science fiction" Titre="Le meilleur des mondes" Auteur="Aldous Huxley" DatePar="1988-01-01" Editeur="Pocket" Format="Poche" PrixN="4.2" ISBN="2266023101" />
    <livres Categorie="Science fiction" Titre="1984" Auteur="George Orwell" DatePar="1994-01-25" Editeur="Gallimard" Format="Broché" PrixN="8.4" ISBN="2070386686" />
    <livres Categorie="Science fiction" Titre="La guerre des mondes" Auteur="H. G. Wells" DatePar="1998-03-24" Editeur="Gallimard" Format="Poche" PrixN="11.1" ISBN="2070403343" />
    <livres Categorie="Science" Titre="Maths DEUG MIAS, SM. Tout le premier semestre ! 2ème Édition" Auteur="Valérie Collet" DatePar="2002-04-01" Editeur="Ellipses Marketing" Format="Broché" PrixN="14.5" ISBN="2729811230" />
    <livres Categorie="Science" Titre="Leçons sur la gravitation" Auteur="Richard Feynman" DatePar="2001-10-25" Editeur="Odile Jacob" Format="Broché" PrixN="69" ISBN="273811038X" />
    <livres Categorie="Science" Titre="Réactions chimiques dangereuses" Auteur="Jacques Leleu, Jérôme Triolet" DatePar="2003-09-01" Editeur="Inrs" Format="Broché" PrixN="50.82" ISBN="285599778X" />
    <livres Categorie="Science" Titre="Poussières d\'étoiles" Auteur="Hubert Reeves" DatePar="1998-05-01" Editeur="Seuil" Format="Poche" PrixN="8.5" ISBN="2020224070" />
    <livres Categorie="Science" Titre="La double hélice" Auteur="Watson" DatePar="1999-04-07" Editeur="Hachette Littérature" Format="Poche" PrixN="9.2" ISBN="2012789757" />
    <livres Categorie="Informatique" Titre="JAVA 2 - Plate-forme" Auteur="Rogers Cadenhead" DatePar="2000-09-30" Editeur="Campus Press" Format="Broché" PrixN="9.45" ISBN="2744006971" />
    <livres Categorie="Informatique" Titre="XML et Java" Auteur="Nicholas Chase" DatePar="2001-07-15" Editeur="CampusPress" Format="Broché" PrixN="25.76" ISBN="2744011665" />
    <livres Categorie="Informatique" Titre="SVG : Production orientée XML de graphiques vectoriels" Auteur="J.David Eisenberg" DatePar="2003-03-20" Editeur="O\'Reilly" Format="Broché" PrixN="76" ISBN="2841772284" />
    <livres Categorie="Informatique" Titre="Programmer en Prolog" Auteur="Nigel Ford" DatePar="1993-02-08" Editeur="Dunod" Format="Broché" PrixN="32.5" ISBN="204019827X" />
    <livres Categorie="Informatique" Titre="L\'intelligence des réseaux" Auteur="Derrick de Kerckhove" DatePar="2000-10-01" Editeur="Odile Jacob" Format="Broché" PrixN="22.87" ISBN="2738108962" />
    <livres Categorie="Roman" Titre="Dix petits nègres" Auteur="Agatha Christie" DatePar="2002-11-06" Editeur="LGF" Format="Poche" PrixN="5.2" ISBN="2253003964" />
    <livres Categorie="Romans Policiers" Titre="Tokyo chaos" Auteur="Tokyo chaos" DatePar="2004-01-15" Editeur="Pocket" Format="Poche" PrixN="6.5" ISBN="2266108239" />
    <livres Categorie="Romans Policiers" Titre="Chair et sang" Auteur="Jonathan Kellerman" DatePar="2003-05-06" Editeur="Seuil" Format="Broché" PrixN="20.0" ISBN="2020525240" />
    <livres Categorie="Romans Policiers" Titre="Les Egouts de Los Angeles" Auteur="Michael Connelly" DatePar="1998-01-01" Editeur="Points" Format="Poche" PrixN="13.45" ISBN="2020235250" />
    <livres Categorie="Romans Policiers" Titre="Le Tueur des ombres" Auteur="Val McDermid" DatePar="2003-03-01" Editeur="J\'ai lu" Format="Poche" PrixN="16" ISBN="2290324787" />
    <livres Categorie="Bandes dessinées" Titre="Akira, tome 9 : Visions" Auteur="Katsumimo Otomo" DatePar="1993-05-21" Editeur="Glénat" Format="Cartonné" PrixN="14.99" ISBN="272341552X" />
    <livres Categorie="Bandes dessinées" Titre="Love Hina, tome 8" Auteur="Akamatsu" DatePar="2003-03-26" Editeur="Pika" Format="Poche" PrixN="13.9" ISBN="2845992254" />
    <livres Categorie="Bandes dessinées" Titre="Alpha, tome 7 : Snow White, 30 secondes !" Auteur="Mythic" DatePar="2003-10-25" Editeur="Le Lombard" Format="Cartonné" PrixN="9.45" ISBN="2803618354" />
    <livres Categorie="Bandes dessinées" Titre="Witchblade, tome 3" Auteur="Michael Turner" DatePar="2000-06-13" Editeur="USA Editions" Format="Cartonné" PrixN="11.5" ISBN="2911033418" />
    <livres Categorie="Bandes dessinées" Titre="Nomad, tome 5 : Mémoire cachée" Auteur="Jean-David Morvan" DatePar="2000-09-12" Editeur="Glénat" Format="Cartonné" PrixN="14.99" ISBN="2723426890" />
    <livres Categorie="Science fiction" Titre="Le Seigneur des anneaux" Auteur="John Ronald Reuel Tolkien" DatePar="2003-10-08" Editeur="Christian Bourgois" Format="Broché" PrixN="24.7" ISBN="2267013169" />
    <livres Categorie="Science fiction" Titre="La cité des permutants" Auteur="Greg Egan" DatePar="1999-12-01" Editeur="LGF - Livre de Poche" Format="Poche" PrixN="12.8" ISBN="2253072249" />
    <livres Categorie="Science fiction" Titre="Tous à Zanzibar" Auteur="John Brunner" DatePar="1995-01-01" Editeur="LGF - Livre de Poche" Format="Poche" PrixN="14.72" ISBN="2253071803" />
    <livres Categorie="Science fiction" Titre="La fin du a" Auteur="Van Vogt a.E." DatePar="2001-08-13" Editeur="J\'ai lu" Format="Poche" PrixN="9.0" ISBN="2290313149" />
    <livres Categorie="Science fiction" Titre="Le monde des a" Auteur=" Van Vogt a.E." DatePar="2001-04-25" Editeur="J\'ai lu" Format="Poche" PrixN="9.0" ISBN="2290312983" />
    <livres Categorie="Science" Titre="15 semaines de kholles en chimie : MPSI-PCSI, PTSI-BCPST, classes prépas integrées" Auteur="Andrée Baumy" DatePar="2001-07-13" Editeur="Ellipses Marketing" Format="Broché" PrixN="30.00" ISBN="272980353X" />
    <livres Categorie="Science" Titre="Problèmes corrigés de biologie posés aux concours de agro-véto : INA-ENSA, ENV, ENSG Nancy, Archimèd" Auteur="Agnès Lefranc" DatePar="2000-01-01" Editeur="Ellipses Marketing" Format="Broché" PrixN="17.00" ISBN="272980420X" />
    <livres Categorie="Science" Titre="Liberté et neurobiologie" Auteur="John R. Searle" DatePar="2004-01-14" Editeur="Grasset" Format="Broché" PrixN="12.00" ISBN="2246640318" />
    <livres Categorie="Science" Titre="La Gestion Electronique Documentaire" Auteur="Larcher" DatePar="2004-01-15" Editeur="Dunod - 01 Informatique" Format="Broché" PrixN="35.00" ISBN="2100078917" />
    <livres Categorie="Science" Titre="La théorie du chaos : Vers une nouvelle science" Auteur="James Gleick" DatePar="1999-01-04" Editeur="Champs Flammarion Sciences" Format="Poche" PrixN="10.00" ISBN="208081219X" />
    <livres Categorie="Informatique" Titre="Pratique de MySQL et PHP" Auteur="Philippe Rigaux" DatePar="2003-01-23" Editeur="O\'Reilly" Format="Broché" PrixN="33.00" ISBN="2841772373" />
    <livres Categorie="Informatique" Titre="Linux en concentré" Auteur="Ellen Siever" DatePar="2003-11-27" Editeur="O\'Reilly" Format="Broché" PrixN="58.00" ISBN="2841772772" />
    <livres Categorie="Informatique" Titre="Introduction à Java" Auteur="Patrick Niemeyer" DatePar="2002-12-01" Editeur="O\'Reilly" Format="Broché" PrixN="49.00" ISBN="2841772349" />
    <livres Categorie="Informatique" Titre="HTML et XHTML : La Référence" Auteur="Chuck Musciano" DatePar="2001-02-14" Editeur="O\'Reilly" Format="Broché" PrixN="41.00" ISBN="2841771326" />
    <livres Categorie="Informatique" Titre="JavaScript en action" Auteur="Jerry Bradenbaugh" DatePar="2001-11-07" Editeur="O\'Reilly" Format="Broché" PrixN="38.00" ISBN="2841771350" />
    <livres Categorie="Romans Policiers" Titre="L.A. confidential" Auteur="James Ellroy" DatePar="1988-06-02" Editeur="Arrow" Format="Broché" PrixN="11.43" ISBN="0099366711" />
    <livres Categorie="Romans Policiers" Titre="La Proie" Auteur="Michael Crichton" DatePar="2003-10-09" Editeur="Robert Laffont" Format="Broché" PrixN="22.00" ISBN="2221097890" />
    <livres Categorie="Romans Policiers" Titre="L\'Empire des loups" Auteur="Jean-Christophe Grangé" DatePar="2003-01-08" Editeur="Albin Michel" Format="Broché" PrixN="22.00" ISBN="222613624X" />
    <livres Categorie="Romans Policiers" Titre="In Tenebris" Auteur="Maxime Chattam" DatePar="2003-03-06" Editeur="Michel Lafon" Format="Broché" PrixN="20.00" ISBN="2840989042" />
    <livres Categorie="Romans Policiers" Titre="Les Rivières pourpres" Auteur="Jean-Christophe Grangé" DatePar="2001-02-07" Editeur="Le Livre de Poche" Format="Broché" PrixN="6.10" ISBN="2253171670" />
    <livres Categorie="Bandes dessinées" Titre="Titeuf, tome 8 : Le préau atomique" Auteur="Shirley Anguerrand" DatePar="2003-07-02" Editeur="Hachette Jeunesse" Format="Cartonné" PrixN="4.50" ISBN="2012007945" />
    <livres Categorie="Bandes dessinées" Titre="Astérix le Gaulois (version luxe)" Auteur="Albert Uderzo" DatePar="1999-11-09" Editeur="Albert René" Format="Cartonné" PrixN="22.71" ISBN="2864971348" />
    <livres Categorie="Bandes dessinées" Titre="Love Hina, tome 11" Auteur="Akamatsu" DatePar="2003-10-21" Editeur="Pika" Format="Broché" PrixN="6.95" ISBN="2845992742" />
    <livres Categorie="Bandes dessinées" Titre="Kimengumi : collège Fou Fou Fou" Auteur="Motoci Shinzawa" DatePar="1999-08-11" Editeur="Tonkam" Format="Poche" PrixN="9.00" ISBN="2845801173" />
    <livres Categorie="Bandes dessinées" Titre="Nausicaä de la vallée du vent, tome 1" Auteur="Hayao Miyazaki" DatePar="2000-08-16" Editeur="Glénat" Format="Broché" PrixN="10.55" ISBN="2723432971" />
    <livres Categorie="Science fiction" Titre="Le Livre du voyage" Auteur="Bernard Werber" DatePar="2001-03-01" Editeur="LGF - Livre de Poche" Format="Broche - 160 pages" PrixN="8.98" ISBN="2253150185" />
    <livres Categorie="Science fiction" Titre="Encyclopedie du savoir relatif et absolu" Auteur="Bernard Werber" DatePar="2001-09-17" Editeur="LGF - Livre de Poche" Format="Poche - 270 pages" PrixN="16.63" ISBN="2253155306" />
